#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : waffle
Version  : 1.6.0
Release  : 3
URL      : https://gitlab.freedesktop.org/mesa/waffle/-/archive/v1.6.0/waffle-v1.6.0.tar.gz
Source0  : https://gitlab.freedesktop.org/mesa/waffle/-/archive/v1.6.0/waffle-v1.6.0.tar.gz
Summary  : a library for selecting an OpenGL API and window system at runtime
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0
Requires: waffle-bin = %{version}-%{release}
Requires: waffle-data = %{version}-%{release}
Requires: waffle-lib = %{version}-%{release}
Requires: waffle-license = %{version}-%{release}
BuildRequires : bash-completion-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(x11-xcb)

%description
CMOCKA
=======
cmocka is a fork for Google's cmockery unit testing framework to fix bugs and
support it in future.
See https://code.google.com/p/cmockery/

%package bin
Summary: bin components for the waffle package.
Group: Binaries
Requires: waffle-data = %{version}-%{release}
Requires: waffle-license = %{version}-%{release}

%description bin
bin components for the waffle package.


%package data
Summary: data components for the waffle package.
Group: Data

%description data
data components for the waffle package.


%package dev
Summary: dev components for the waffle package.
Group: Development
Requires: waffle-lib = %{version}-%{release}
Requires: waffle-bin = %{version}-%{release}
Requires: waffle-data = %{version}-%{release}
Provides: waffle-devel = %{version}-%{release}
Requires: waffle = %{version}-%{release}

%description dev
dev components for the waffle package.


%package doc
Summary: doc components for the waffle package.
Group: Documentation

%description doc
doc components for the waffle package.


%package lib
Summary: lib components for the waffle package.
Group: Libraries
Requires: waffle-data = %{version}-%{release}
Requires: waffle-license = %{version}-%{release}

%description lib
lib components for the waffle package.


%package license
Summary: license components for the waffle package.
Group: Default

%description license
license components for the waffle package.


%prep
%setup -q -n waffle-v1.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559718582
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/waffle
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/waffle/LICENSE.txt
cp third_party/cmocka/COPYING %{buildroot}/usr/share/package-licenses/waffle/third_party_cmocka_COPYING
cp third_party/cmocka/cmake/Modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/waffle/third_party_cmocka_cmake_Modules_COPYING-CMAKE-SCRIPTS
cp third_party/getopt/LICENSE %{buildroot}/usr/share/package-licenses/waffle/third_party_getopt_LICENSE
cp third_party/threads/LICENSE %{buildroot}/usr/share/package-licenses/waffle/third_party_threads_LICENSE
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wflinfo

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/wflinfo

%files dev
%defattr(-,root,root,-)
/usr/include/waffle-1/waffle.h
/usr/include/waffle-1/waffle_gbm.h
/usr/include/waffle-1/waffle_glx.h
/usr/include/waffle-1/waffle_version.h
/usr/include/waffle-1/waffle_wayland.h
/usr/include/waffle-1/waffle_x11_egl.h
/usr/lib64/libwaffle-1.so
/usr/lib64/pkgconfig/waffle-1.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/waffle1/HACKING.txt
/usr/share/doc/waffle1/LICENSE-threads.txt
/usr/share/doc/waffle1/LICENSE.txt
/usr/share/doc/waffle1/README.md
/usr/share/doc/waffle1/examples/Makefile.example
/usr/share/doc/waffle1/examples/gl_basic.c
/usr/share/doc/waffle1/examples/simple-x11-egl.c
/usr/share/doc/waffle1/release-notes/waffle-0.1.txt
/usr/share/doc/waffle1/release-notes/waffle-0.2.txt
/usr/share/doc/waffle1/release-notes/waffle-0.3.0.txt
/usr/share/doc/waffle1/release-notes/waffle-0.3.1.txt
/usr/share/doc/waffle1/release-notes/waffle-1.0.0.txt
/usr/share/doc/waffle1/release-notes/waffle-1.0.1.txt
/usr/share/doc/waffle1/release-notes/waffle-1.1.0.txt
/usr/share/doc/waffle1/release-notes/waffle-1.1.1.txt
/usr/share/doc/waffle1/release-notes/waffle-1.1.2.txt
/usr/share/doc/waffle1/release-notes/waffle-1.2.0.txt
/usr/share/doc/waffle1/release-notes/waffle-1.2.1.txt
/usr/share/doc/waffle1/release-notes/waffle-1.2.2.txt
/usr/share/doc/waffle1/release-notes/waffle-1.3.0.txt
/usr/share/doc/waffle1/release-notes/waffle-1.4.0.txt
/usr/share/doc/waffle1/release-notes/waffle-1.4.1.txt
/usr/share/doc/waffle1/release-notes/waffle-1.4.2.txt
/usr/share/doc/waffle1/release-notes/waffle-1.4.3.txt
/usr/share/doc/waffle1/release-notes/waffle-1.4.4.txt
/usr/share/doc/waffle1/release-notes/waffle-1.5.0.txt
/usr/share/doc/waffle1/release-notes/waffle-1.5.1.txt
/usr/share/doc/waffle1/release-notes/waffle-1.5.2.txt
/usr/share/doc/waffle1/release-notes/waffle-1.6.0.md

%files lib
%defattr(-,root,root,-)
/usr/lib64/libwaffle-1.so.0
/usr/lib64/libwaffle-1.so.0.6.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/waffle/LICENSE.txt
/usr/share/package-licenses/waffle/third_party_cmocka_COPYING
/usr/share/package-licenses/waffle/third_party_cmocka_cmake_Modules_COPYING-CMAKE-SCRIPTS
/usr/share/package-licenses/waffle/third_party_getopt_LICENSE
/usr/share/package-licenses/waffle/third_party_threads_LICENSE
